name: Auto-publish

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.settings.platform }}
    strategy:
      matrix:
        settings:
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "macos-14"
            args: "--target aarch64-apple-darwin"
          - platform: "windows-latest"
            args: "--target x86_64-pc-windows-msvc"
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install project and dependencies
        run: pip install .

      - name: Build application with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon=youtube_bulk_upload/logo.png --name=YouTubeBulkUpload youtube_bulk_upload/gui.py

      - name: Extract architecture
        run: echo "ARCHITECTURE=$(echo '${{ matrix.settings.args }}' | cut -d' ' -f2 | cut -d'-' -f1)" >> $GITHUB_ENV

      # Install create-dmg (Only for macOS)
      - name: Install create-dmg
        if: startsWith(matrix.settings.platform, 'macos')
        run: npm install -g create-dmg

      # Create DMG (Only for macOS)
      - name: Create DMG
        if: startsWith(matrix.settings.platform, 'macos')
        run: create-dmg 'dist/YouTubeBulkUpload.app' --dmg-title="YouTubeBulkUpload"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: YouTubeBulkUpload-${{ runner.os }}-${{ env.ARCHITECTURE }}-${{ github.run_number }}
          path: |
            dist/YouTubeBulkUpload*.app
            dist/YouTubeBulkUpload*.exe
            dist/*.dmg

  # Auto-publish when version is increased
  publish-pypi:
    # Only publish on `main` branch
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions: # Don't forget permissions
      contents: write

    steps:
      - uses: etils-actions/pypi-auto-publish@v1
        with:
          pypi-token: ${{ secrets.PYPI_API_TOKEN }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          parse-changelog: false
