name: Auto-publish

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.settings.platform }}
    strategy:
      matrix:
        settings:
          - platform: "macos-13"
            args: "--target x86_64-apple-darwin"
          - platform: "macos-14"
            args: "--target aarch64-apple-darwin"
          - platform: "windows-latest"
            args: "--target x86_64-pc-windows-msvc"
    steps:
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APPNAMEWITHDETAILS }}-${{ matrix.settings.platform }}
          path: |
            ${{ startsWith(matrix.settings.platform, 'windows') && format('dist/{0}.exe', env.APPNAMEWITHDETAILS) || '' }}
            ${{ startsWith(matrix.settings.platform, 'macos') && format('dist/{0}.dmg', env.APPNAMEWITHDETAILS) || '' }}

  publish-pypi:
    needs: [build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Flatten artifacts into a single directory
        run: |
          mkdir -p flattened_artifacts
          find artifacts -type f -exec mv -v {} flattened_artifacts/ \;

      - name: Publish to PyPI and create GitHub release
        uses: etils-actions/pypi-auto-publish@v1
        with:
          pypi-token: ${{ secrets.PYPI_API_TOKEN }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          parse-changelog: false

      - name: Extract version from pyproject.toml
        id: version
        run: |
          VERSION=$(grep 'version =' pyproject.toml | awk -F'"' '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload assets to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.version.outputs.version }}"
          files: flattened_artifacts/*
